info:
  contact: {}
  license: {}
paths:
  /system/health:
    get:
      description: 描述信息
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 健康检查API
      tags:
      - 系统管理
  /user/info/:id:
    get:
      description: 获取单个用户信息
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: 获取单个用户信息API
      tags:
      - 用户管理
swagger: "2.0"
